# Generated by Django 4.1.1 on 2023-03-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('pic', models.ImageField(default='', upload_to='img/')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
