# Generated by Django 4.1.1 on 2023-03-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='arrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='arrivals/')),
                ('mrp', models.FloatField()),
                ('sellingprice', models.FloatField()),
            ],
            options={
                'db_table': 'arrivals',
            },
        ),
        migrations.CreateModel(
            name='featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='featured/')),
                ('mrp', models.FloatField()),
                ('sellingprice', models.FloatField()),
            ],
            options={
                'db_table': 'featured',
            },
        ),
    ]
