# Generated by Django 4.1.1 on 2023-04-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_english_hindi_punjabi'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='featured',
            name='isbn',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='featured',
            name='no_of_pages',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='featured',
            name='publishdate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='featured',
            name='publisher',
            field=models.CharField(default='', max_length=100),
        ),
    ]
