# Generated by Django 4.1.1 on 2023-04-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_featured_author_featured_isbn_featured_no_of_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivals',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='arrivals',
            name='isbn',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='arrivals',
            name='no_of_pages',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='arrivals',
            name='publishdate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='arrivals',
            name='publisher',
            field=models.CharField(default='', max_length=100),
        ),
    ]
