# Generated by Django 4.1.1 on 2023-04-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_arrivals_author_arrivals_isbn_arrivals_no_of_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='english',
            name='isbn',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='english',
            name='no_of_pages',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='english',
            name='publishdate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='english',
            name='publisher',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hindi',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hindi',
            name='isbn',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hindi',
            name='no_of_pages',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hindi',
            name='publishdate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hindi',
            name='publisher',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='punjabi',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='punjabi',
            name='isbn',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='punjabi',
            name='no_of_pages',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='punjabi',
            name='publishdate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='punjabi',
            name='publisher',
            field=models.CharField(default='', max_length=100),
        ),
    ]
