# Generated by Django 4.1.1 on 2023-04-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_english_author_english_isbn_english_no_of_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='booktype',
            field=models.CharField(blank=True, choices=[('New Arrival', 'New Arrival'), ('English', 'English'), ('Hindi', 'Hindi'), ('Punjabi', 'Punjabi'), ('Best Seller', 'Best Seller'), ('Featured', 'Featured'), ('Action', 'Action'), ('Adventure', 'Adventure')], default='', max_length=50, null=True),
        ),
    ]
