# Generated by Django 4.1.1 on 2023-05-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_blog_description_blog_name_blog_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='postby',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='poston',
            field=models.CharField(default='', max_length=100),
        ),
    ]
